_security_logout:
    resource: security.route_loader.logout
    type: service

# Lexik JWT Authentication Bundle routes
api_login_check:
    path: /api/login_check

api_token_refresh:
    path: /api/token/refresh